# 自動生成されたファイルを対象外にする
AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'Gemfile'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Metrics/AbcSize:
  Max: 30

ClassAndModuleChildren:
  EnforcedStyle: compact

MethodLength:
  Max: 20
