default_url_options:
  host: 'https://oyatsu300.herokuapp.com/'
twitter:
  callback_url: 'https://oyatsu300.herokuapp.com/oauth/callback?provider=twitter'
redis:
  servers: 'oyatsu300-redis.hkx8gy.ng.0001.apne1.cache.amazonaws.com:6379'
